/* TABLE CATEGORIA */
DROP TABLE IF EXISTS Categoria;

CREATE TABLE IF NOT EXISTS Categoria (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100)
);

INSERT INTO Categoria(NOME) VALUES ('Saladas');
INSERT INTO Categoria(NOME) VALUES ('Sopas');
INSERT INTO Categoria(NOME) VALUES ('Massas');
INSERT INTO Categoria(NOME) VALUES ('Carnes');
INSERT INTO Categoria(NOME) VALUES ('Sobremesas');

/* TABLE TAGS */
DROP TABLE IF EXISTS Tag;

CREATE TABLE IF NOT EXISTS Tag (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100)
);

INSERT INTO Tag(NOME) VALUES ('Rápidas');
INSERT INTO Tag(NOME) VALUES ('Light');
INSERT INTO Tag(NOME) VALUES ('Vegetariana');
INSERT INTO Tag(NOME) VALUES ('Vegana');
INSERT INTO Tag(NOME) VALUES ('Sem forno');